### ISSUE TITLE
how to build dcoker image

### ISSUE THREAD

**Issue by YYTB** [rwv/lookscanned.io#10]
i try to make a docker image use this dockerfile 

```dockerfile
FROM node
EXPOSE 4173 5050
WORKDIR /home/node/lookscanned
COPY lookscanned.io-main /home/node/lookscanned
RUN yarn add esbuild && npm run build:all
CMD npm run serve --host 0.0.0.0 --port 4173
```

but won't work, can you help?

**Comment by rwv** [comment]
You may need to `npm install` first
Is there any log?

**Comment by rwv** [comment]
Because this issue doesn't relate to `lookscanned.io` itself, I will close this issue.
But feel free to comment.
