### ISSUE TITLE
keep source confidential: pdf metadata shows that is has been crafted using web technologies

### ISSUE THREAD

**Issue by Semnodime** [rwv/lookscanned.io#146]
run `strings` against the output file and there are hints easily spotted, that the scan is fake.
I'd suggest removing any artefact which provably concludes this was created using web technologies like javascript.

`/Producer (jsPDF 2.5.1)`

**Comment by rwv** [comment]
This is hard-coded in jsPDF, [code](https://github.com/parallax/jsPDF/blob/5d09af9135a2fe049c7d3c8b95df280d22e4a6db/src/jspdf.js#L2859). Need to find other way to change Producer text.

**Comment by ajimix** [comment]
You can add a post `npm install` script that removes that line from the installed jsPDF project

**Comment by seferdemirci** [comment]
pdf-lib package can do that. before saving file to local, you can change "producer" exif metadata.

**Comment by rwv** [comment]
Fixed with `TODO: use custom metadata provided by user`

**Comment by rwv** [comment]
https://github.com/rwv/lookscanned.io/blob/816def4cc4a7bb8d062f22d7e1c11851fc52e91a/src/utils/pdf-builder/pdf-lib/build-pdf.ts#L45-L48
