### ISSUE TITLE
构建后的\dist下的index.html双击打开后显示空白

### ISSUE THREAD

**Issue by mr-zhanghao-f** [rwv/lookscanned.io#170]
构建后的\dist下的index.html双击打开后显示空白

先用了：
npm install
npm run build

index.html双击打开后显示空白
（\dist下的index.html）

**Comment by mr-zhanghao-f** [comment]
在浏览器检查页面源码：
<html>
<body>

  | <!DOCTYPE html>
-- | --
  | <html lang="en">
  | <head>
  | 
  | <link rel="icon" href="/favicon.ico" media="(prefers-color-scheme: light)">
  | <link rel="icon" href="/favicon-dark.ico" media="(prefers-color-scheme: dark)">
  | <link rel="icon" href="/favicon.svg" type="image/svg+xml">
  | <link rel="apple-touch-icon" href="/apple-touch-icon.png" sizes="180x180">
  | <link rel="mask-icon" href="/mask-icon.svg" color="#7e7e7e">
  | <meta name="viewport" content="width=device-width, initial-scale=1.0">
  | <title>PDF InBrowser.App</title>
  | <meta name="description" content="PDF InBrowser.App is a tool to handle PDFs. Fully runs in your browser, no data is sent to the server. Fast, secure, and offline capable.">
  | <meta name="theme-color" content="#ffffff" media="(prefers-color-scheme: light)">
  | <meta name="theme-color" content="#101014" media="(prefers-color-scheme: dark)">
  | <style>@media (prefers-color-scheme:dark){body{background-color:#101014}}</style>
  | <script type="module" crossorigin src="/assets/index-1839e320.js"></script>
  | <link rel="stylesheet" href="/assets/index-10a88d37.css">
  | <link rel="manifest" href="/manifest.webmanifest"><script id="vite-plugin-pwa:register-sw" src="/registerSW.js"></script></head>
  | <body>
  | <div id="app"></div>
  |  
  | </body>
  | </html>


</body>
</html><!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <link rel="icon" href="[/favicon.ico](https://github.com/favicon.ico)" media="(prefers-color-scheme: light)">
    <link rel="icon" href="[/favicon-dark.ico](https://github.com/favicon-dark.ico)" media="(prefers-color-scheme: dark)">
    <link rel="icon" href="[/favicon.svg](https://github.com/favicon.svg)" type="image/svg+xml">
    <link rel="apple-touch-icon" href="[/apple-touch-icon.png](https://github.com/apple-touch-icon.png)" sizes="180x180">
    <link rel="mask-icon" href="[/mask-icon.svg](https://github.com/mask-icon.svg)" color="#7e7e7e">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PDF InBrowser.App</title>
    <meta name="description" content="PDF InBrowser.App is a tool to handle PDFs. Fully runs in your browser, no data is sent to the server. Fast, secure, and offline capable.">
    <meta name="theme-color" content="#ffffff" media="(prefers-color-scheme: light)">
    <meta name="theme-color" content="#101014" media="(prefers-color-scheme: dark)">
    <style>@media (prefers-color-scheme:dark){body{background-color:#101014}}</style>
    <script type="module" crossorigin src="[/assets/index-1839e320.js](https://github.com/assets/index-1839e320.js)"></script>
    <link rel="stylesheet" href="[/assets/index-10a88d37.css](https://github.com/assets/index-10a88d37.css)">
  <link rel="manifest" href="[/manifest.webmanifest](https://github.com/manifest.webmanifest)"><script id="vite-plugin-pwa:register-sw" src="[/registerSW.js](https://github.com/registerSW.js)"></script></head>
  <body>
    <div id="app"></div>
    
  </body>
</html>

**Comment by rwv** [comment]
不能双击打开，要用一个正经的 http server

**Comment by mr-zhanghao-f** [comment]
感谢您，已经顺利解决！



------2VEIRSE2ZDQXZ10BHASV9YIENV0B9O
Content-Type: text/html;
 charset=utf-8
Content-Transfer-Encoding: 8bit

<html><body><html><body><span style="background-color: rgb(255, 255, 255);">感谢您，已经顺利解决！</span></body></html><br>
<br>
<br>
<p style="margin: 5px 0 0 0;padding: 0;font-size: 13px;color: #929292;line-height: 20px;"></p>

</body></html>
------2VEIRSE2ZDQXZ10BHASV9YIENV0B9O--
