### ISSUE TITLE
Make paper look recycled yellowish

### ISSUE THREAD

**Issue by TheMinefighter** [rwv/lookscanned.io#222]
Using `+level-colors ,'rgb(242,226,202)'` one could make the paper look like non-bleached recycled paper, optionally with an intensity slider (linearly transforming above values to 255 each). What do you think of that? I think this would help the authenticity of the results a lot
EDIT: Optimized numbers

**Comment by rwv** [comment]
Can you provide an example? Thank you!

**Comment by TheMinefighter** [comment]
Of course: this is my one-page example
[Example-Original.pdf](https://github.com/user-attachments/files/17172820/Example-Original.pdf)
This is it after going through lookscanned
[Example-scan.pdf](https://github.com/user-attachments/files/17172821/Example-scan.pdf)
And this is it after adding the suggested effect
[Example-scan-tinted.pdf](https://github.com/user-attachments/files/17172824/Example-scan-tinted.pdf)
It looks like a piece of non-bleach recycling paper that has been sitting around somewhere. 

As a default I would suggest a strength of 50% of this effect, looking like that:
[Example-scan-less_tinted.pdf](https://github.com/user-attachments/files/17172827/Example-scan-less_tinted.pdf)

Although I don't have much experience in TS I might be able to implement that myself

**Comment by ajimix** [comment]
I'm also interested in this

**Comment by ajimix** [comment]
@TheMinefighter I've implemented it in #225 

I used fill combined with colorize, which gave me better results after several tests. Let's hope someone can merge it so everyone can enjoy

**Comment by nonubot123** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
