### ISSUE TITLE
Not working online Firefox M1

### ISSUE THREAD

**Issue by KevinColemanInc** [rwv/lookscanned.io#31]
I have a Macbook m1 and it the website is stuck on "Combining PDF pages" for a single page pdf of a screen shot with Firefox 100.0.2 (64-bit).

```
Warning: fetchStandardFontData: failed to fetch file "FoxitSymbol.pfb" with "UnknownErrorException: StandardFontDataFactory not initialized, see the `useWorkerFetch` parameter.". 4 [pdf.worker.min.4ac4c8ea.js:22:21471](https://lookscanned.io/assets/pdf.worker.min.4ac4c8ea.js)
start Worker [index.44c81b0c.js:21:23008](https://lookscanned.io/assets/index.44c81b0c.js)
Message received from main script 2 [processImage.worker.e046c828.js:174:865](https://lookscanned.io/assets/processImage.worker.e046c828.js)
start Worker [index.44c81b0c.js:21:23008](https://lookscanned.io/assets/index.44c81b0c.js)
Message received from main script 2 [processImage.worker.e046c828.js:174:865](https://lookscanned.io/assets/processImage.worker.e046c828.js)
rendered page 1/1 [index.44c81b0c.js:25:68164](https://lookscanned.io/assets/index.44c81b0c.js)
start Worker [index.44c81b0c.js:21:23008](https://lookscanned.io/assets/index.44c81b0c.js)
Message received from main script 2 [processImage.worker.e046c828.js:174:865](https://lookscanned.io/assets/processImage.worker.e046c828.js)
processed page 1/1 [index.44c81b0c.js:25:68235](https://lookscanned.io/assets/index.44c81b0c.js)
Worker combineImagesToPdf: Received message from main script 2 [combineImagesToPdf.worker.c9f15f56.js:174:92](https://lookscanned.io/assets/combineImagesToPdf.worker.c9f15f56.js)
```

It does not work in Chrome (Version 102.0.5005.61 (Official Build) (arm64)). Chrome asks were to save the file, but nothing is downloaded into the file.

To reproduce:

Take a screen shot.
Open the screen shot in MacOS preview.
Print to pdf.
Upload the pdf to the website.
Hit save.
{wait forever}

**Comment by rwv** [comment]
Thank you!
Recently, I did some optimizations for worker script. However forgot to call the process function in the worker script which caused this to happen.

**Comment by KevinColemanInc** [comment]
It worked in Incognito Chrome, but couldn't get it to work in Firefox or Firefox incognito. Thanks!

**Comment by rwv** [comment]
Weird... Firefox works fine for me. Could you provide any log?

**Comment by KevinColemanInc** [comment]
This one, I uploaded an pdf. it got stuck. tried a few more times. still stuck:

<img width="1509" alt="image" src="https://user-images.githubusercontent.com/2381771/170633527-b8424189-6a26-4425-a98a-0f104bdee652.png">

This one I uploaded it once:
<img width="1498" alt="image" src="https://user-images.githubusercontent.com/2381771/170633613-18eb44f6-077c-4e6b-a5b3-4a617b65a203.png">
