### ISSUE TITLE
How to build an offline portable version in Windows system?

### ISSUE THREAD

**Issue by Huaweidev** [rwv/lookscanned.io#49]
Hi,
How to build an offline portable version in Windows system? It will be more convenient for office without WAN connection.

**Comment by rwv** [comment]
You can use electron to build offline app.  Another choice is to setup a web server, for example nginx, to host the static files

**Comment by rwv** [comment]
For now, there is no official timeline to build an offline portable version. Close this issue but feel free to comment.
