### ISSUE TITLE
How to use the offline version? Index.html in the root directory after code download cannot be used

### ISSUE THREAD

**Issue by jiaoting** [rwv/lookscanned.io#88]
How to use the offline version? Index.html in the root directory after code download cannot be used

**Comment by rwv** [comment]
Could you describe your code downloading? Just `git clone` or download `index.html`

**Comment by jiaoting** [comment]
![image](https://user-images.githubusercontent.com/12553424/182120285-b9f8dd04-1ebc-4086-8526-27c3f62f9807.png)
![image](https://user-images.githubusercontent.com/12553424/182120357-8d08f576-7d8d-404b-9700-990ddf6fc628.png)
![image](https://user-images.githubusercontent.com/12553424/182120394-dc312785-be1c-43a8-91df-f2f3a3e5b276.png)
nothing。。。

**Comment by rwv** [comment]
You need to compile source files using  `npm run build` and you can find all compiled files in `dist` folder.
